# These are supported funding model platforms

github: [NjabuloJf]
patreon: ➥ sir Njabulo Jbメ
open_collective: fanaAI
ko_fi: fana
tidelift: Njabulo Jb 
community_bridge: GWM-XMD 
liberapay: bot
issuehunt: happiness 
otechie: momentbot 
custom: ["https://njabulo-com.vercel.app/"]
